version: "3.9"

services:

  backend:
    build: ./backend
    container_name: pencil_backend
    ports:
      - "5000:5000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=mytoken
      - INFLUX_ORG=pencilorg
      - INFLUX_BUCKET=production
    depends_on:
      influxdb:
        condition: service_healthy
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: pencil_influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=pencilorg
      - DOCKER_INFLUXDB_INIT_BUCKET=production
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    volumes:
      - influx_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: pencil_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: pencil_hmi
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      
    restart: unless-stopped

volumes:
  influx_data:
  grafana_data:
